// <auto-generated />
namespace SchoolExpress.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_Self_Reference_One_To_One_On_Table_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Self_Reference_One_To_One_On_Table_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201804221707480_Add_Self_Reference_One_To_One_On_Table_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
