INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES ( 1,  1, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES ( 2,  2, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES ( 3,  3, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES ( 4,  4, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES ( 5,  5, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES ( 6,  6, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES ( 7,  7, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES ( 8,  8, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES ( 9,  9, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (10, 10, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (11, 11, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (12, 12, 150, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (13, 13, 240, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (14, 14, 240, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (15, 15, 300, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (16, 16, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (17, 17, 300, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (18, 18, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (19, 19, 300, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (20, 20, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (21, 21, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (22, 22, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (23, 23, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (24, 24, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (25, 25, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (26, 26, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (27, 27, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (28, 28, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (29, 29, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (30, 30, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (31, 31, 180, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (32, 32, 150, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (33, 33, 240, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (34, 34, 240, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (35, 35, 300, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (36, 36, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (37, 37, 300, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (38, 38, 210, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (39, 39, 300, GETDATE(), GETDATE(), 1);
INSERT INTO [dbo].[Enrollment] ([Id], [StudentId], [Total], [LastModified], [Created], [Status]) VALUES (40, 40, 210, GETDATE(), GETDATE(), 1);