SET NOCOUNT ON
DBCC CHECKIDENT ('[dbo].[Campus]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[Career]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[CareerDetail]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[CareerSchedule]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[CareerScheduleDetail]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[ClassRoom]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[Course]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[Degree]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[Enrollment]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[Module]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[Period]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[Person]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[Speaker]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[Student]', RESEED, 0) WITH NO_INFOMSGS
DBCC CHECKIDENT ('[dbo].[UserClaim]', RESEED, 0) WITH NO_INFOMSGS