// <auto-generated />
namespace SchoolExpress.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Set_MaxLength_String_Ids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_MaxLength_String_Ids));
        
        string IMigrationMetadata.Id
        {
            get { return "201805020710246_Set_MaxLength_String_Ids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
